name = "cf-post-it"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = "032aa862be071ee175c18b7b6d6f81c2"
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm install && npm run build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "BOARD", class_name = "Board"}]
